### ISSUE TITLE
munmap_chunk(): invalid pointer when building MD tree

### ISSUE THREAD

**Issue by anthonimes** [LyteFM/modular-decomposition#1]
hi! 

i am trying to use your code to compute modular decomposition of (rather) small graphs. 
on the graph given below:

```std::string test = "([0, 1, 2, 3, 4, 5, 6, 7], [{0,1}, {0,6}, {0,4}, {0,7}, {0,5}, {1,0}, {1,6}, {1,4}, {1,7}, {1,5}, {2,6}, {2,4}, {2,7}, {3,6}, {3,4}, {3,7}, {3,5}, {4,1}, {4,0}, {4,2}, {4,6}, {4,7}, {4,3}, {4,5}, {5,1}, {5,0}, {5,6}, {5,4}, {5,7}, {5,3}, {6,1}, {6,0}, {6,2}, {6,4}, {6,7}, {6,3}, {6,5}, {7,1}, {7,0}, {7,2}, {7,6}, {7,4}, {7,3}, {7,5}])";```

the code ends with a munmap_chunk(): invalid pointer error. 
it seems to happen on the calculateModuleType function, but I failed to see where and why... 

i managed to reproduce the issue on different graphs that can provide if needed. 
did this error already occur when running your code?

thanks!

**Comment by anthonimes** [comment]
actually, commenting line 492 of `ModDecomp.cpp` does the job! 
the `boost::degree(*si,tmp)` command goes out of bounds.

it seems this was used in the context of spiders, which is commented afterwards. 

this is just a straightforward hack, but it should not impact the remaining of the code. :)

**Comment by fynnlyte** [comment]
Hello,
cool that you've found and fixed this ;) yeah these lines were just leftovers from the spider recognition which I had uncommented for my purposes. No idea why I haven't noticed it earlier, maybe my graphs were always „prime enough” or it failed silently with older `boost` - versions.
